### ISSUE TITLE
Implement post-conference design

### ISSUE THREAD

**Issue by Wolfr** [svelte-society/svelte-summit-2020#23]
Here's a brief to implement the post-conference design.

If anyone wants to give it a go, or parts of the process. This issue can serve as a master issue. Could be split up in different issues if needed.

## Fix data

We'll need to add the YouTube link to the data:
https://github.com/svelte-society/svelte-summit-2020/blob/master/content.json

All YouTube links can be found on the Svelte Society YouTube channel: https://www.youtube.com/channel/UCZSr5B0l07JXK2FIeWA0-jw

## Implement routes to speaker detail pages

We need to implement routes for all speaker detail pages. This repo uses [Elder.js](https://elderguide.com/tech/elderjs/)

Here's the design for the page with speakers with a button:
https://www.figma.com/file/eGZWK3nGZoOfvTDXzDE5bo/Svelte-Summit?node-id=292%3A929

The speakers page can be a sort of modal, or just a whole separate route that looks very simple.
It can just show the existing data and the youtube embed.

https://www.figma.com/file/eGZWK3nGZoOfvTDXzDE5bo/Svelte-Summit?node-id=292%3A495

![image](https://user-images.githubusercontent.com/12690/97372237-70772080-18b3-11eb-80be-fe29d7e1032d.png)

## Adjust FAQ

We could remove the FAQ like I did and keep the first question but word it a bit differently

> “Welcome to the Svelte Summit post-event website! Svelte Summit was an event dedicated to Svelte and everything that is happening in the community. Participants were able to tune in to a full day of talks and discussions all while chatting to other Svelthusiasts on the Discord server.”

## Move sponsors

We can move the sponsors down a bit now that the event is over.

## (New) Sign up

Adjust copy to signify future event in 2021.

**Comment by swyxio** [comment]
nice one! @kevmodrome do you think we should also email the people who signed up with the list of talks and the conf recaps from @tanhauhau and @vedam? 

also wonder if we should make it clear that we intend to have at least 1 more event in 2021, sign up here for updates etc?

**Comment by kevmodrome** [comment]
Yes, great idea! I'll concoct an email to send out once the website redesign is live!

I'll take a look at implementing this later today 👍

**Comment by Wolfr** [comment]
Right the sign up box should be there for news about future events. This e-mail box is in the code but not in the designs. Good idea @sw-yx !

**Comment by Wolfr** [comment]
I updated the main topic, we could split this up in 5 dev issues OR just do the work ;D
