### ISSUE TITLE
Talk submission

### ISSUE THREAD

**Issue by ghost** [svelte-society/svelte-summit-2020#30]
_I'm aware that this is the wrong place to ask, but I don't know where else I should write this (I don't have a discord account, and there's no generic email address I could reach @svelte-society under)._

Can I still submit a talk? I missed the Call for Speakers deadline. ^^

**Comment by kevmodrome** [comment]
Hi there! The CFPs are unfortunately closed. There will be more events in the future. If you're still interested in doing a talk on our YouTube channel please reach out to us. I'm @kevmodrome on Twitter if you want to get in contact with us 👍
